service: fda

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      - ${file(iam.yml)}
  environment:
    USERS_TABLE: ${self:custom.usersTableName}

functions:
  login:
    handler: src/handlers/auth.login
    events:
      - http:
          path: login
          method: post
          cors: true
  
  generateOtp:
    handler: src/handlers/auth.generateOtp
    events:
      - http:
          path: generate_otp
          method: post
          cors: true

  verifyLogin:
    handler: src/handlers/auth.verifyLogin
    events:
      - http:
          path: verify_login
          method: post
          cors: true

  verifyToken:
    handler: src/handlers/auth.verifyToken
    events:
      - http:
          path: verify_token
          method: post
          cors: true

  getuser_by_id:
    handler: src/handlers/users.getUserById
    events:
      - http:
          path: get_user
          method: post
          cors: true
  create_user:
    handler: src/handlers/users.createUser
    events:
      - http:
          path: create_user
          method: post
          cors: true
  update_user:
    handler: src/handlers/users.updateUser
    events:
      - http:
          path: updateUser
          method: post
          cors: true

  getuser_by_ids:
    handler: src/handlers/users.getUserByIds
    events:
      - http:
          path: getuser_by_ids
          method: post
          cors: true

  query_user_by_filters:
    handler: src/handlers/users.queryUsers
    events:
      - http:
          path: query_user_by_filters
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3002
    lambdaPort: 3003
  usersTableName:  ${self:service}-users 

resources:
  - ${file(resources.yml)}
