service: fda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  dbQuery:
    handler: src/handler.dbQuery
    events:
      - http:
          path: dbquery
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3002
    lambdaPort: 3003
