service: fda

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  get_user:
    handler: src/handlers/users.getUser
    events:
      - http:
          path: get_user
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3002
    lambdaPort: 3003
