service: fda-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  dbquery:
    handler: src/handler.queryHandler
    events:
      - http:
          path: dbquery
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3004
    lambdaPort: 3005

package:
  individually: true

build:
  esbuild:
    bundle: true
    target: node20
    platform: node
    sourcemap: true
