'use strict'

const USER_CUSTOMER_ROLE = 'CUSTOMER'
const USER_VENDOR_ROLE = 'VENDOR'
const USER_ADMIN_ROLE = 'ADMIN'

const USER_ROLES = [USER_CUSTOMER_ROLE, USER_VENDOR_ROLE, USER_ADMIN_ROLE]

const ACC_ACTIVE_STATUS = 'ACTIVE'
const ACC_INACTIVE_STATUS = 'INACTIVE'
const ACCOUNT_STATUSES = [ACC_ACTIVE_STATUS, ACC_INACTIVE_STATUS]

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUSES,
}
