'use strict'

const USER_CUSTOMER_ROLE = 'CUSTOMER'
const USER_VENDOR_ROLE = 'VENDOR'
const USER_ADMIN_ROLE = 'ADMIN'

const USER_TABLE_NAME = 'users'
const RESTAURANT_TABLE_NAME = 'restaurants'
const MENU_ITEM_TABLE_NAME = 'menu_items'
const CATEGORY_TABLE_NAME = 'categories'
const ORDER_TABLE_NAME = 'orders'
const SERVICE = 'fda'

const USER_ROLES = [USER_CUSTOMER_ROLE, USER_VENDOR_ROLE, USER_ADMIN_ROLE]

const ACC_ACTIVE_STATUS = 'ACTIVE'
const ACC_INACTIVE_STATUS = 'INACTIVE'
const PENDING = 'PENDING'
const ONGOING = 'ONGOING'
const COMPLETED = 'COMPLETED'
const ACCOUNT_STATUSES = [ACC_ACTIVE_STATUS, ACC_INACTIVE_STATUS]
const ORDER_STATUSES = [PENDING, ONGOING, COMPLETED]

module.exports = {
  USER_CUSTOMER_ROLE,
  USER_VENDOR_ROLE,
  USER_ADMIN_ROLE,
  USER_ROLES,
  ACC_ACTIVE_STATUS,
  ACC_INACTIVE_STATUS,
  ACCOUNT_STATUSES,
  USER_TABLE_NAME,
  RESTAURANT_TABLE_NAME,
  MENU_ITEM_TABLE_NAME,
  CATEGORY_TABLE_NAME,
  ORDER_TABLE_NAME,
  SERVICE,
  ORDER_STATUSES
}
